module.exports = PhonemeData = [
  {
    phoneme: '/s/',
    id: 1,
    description: 'see, set, sit',
    uniCode: 's',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/p/',
    id: 2,
    description: 'pen, copy, happen',
    uniCode: 'p',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/b/',
    id: 3,
    description: 'back, baby, job',
    uniCode: 'b',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/t/',
    id: 4,
    description: 'tea, tight, button',
    uniCode: 't',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/d/',
    id: 5,
    description: 'day, ladder, odd',
    uniCode: 'd',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/k/',
    id: 6,
    description: 'key, clock, school',
    uniCode: 'k',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/g/',
    id: 7,
    description: 'get, giggle, ghost',
    uniCode: '&#609;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ch/',
    id: 8,
    description: 'church, match, nature',
    uniCode: 't &#643;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/j/',
    id: 9,
    description: 'judge, age, soldier',
    uniCode: 'd &#658;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/f/',
    id: 10,
    description: 'fat, coffee, rough, photo',
    uniCode: 'f',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/v/',
    id: 11,
    description: 'view, heavy, move',
    uniCode: 'v',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/th/',
    id: 12,
    description: 'thing, author, path',
    uniCode: '&#952;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/th/',
    id: 13,
    description: 'this, other, smooth',
    uniCode: '&#240;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/z/',
    id: 14,
    description: 'zero, music, roses, buzz',
    uniCode: 'z',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/sh/',
    id: 15,
    description: 'ship, sure, national',
    uniCode: '&#643;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/zh/',
    id: 16,
    description: 'pleasure, vision',
    uniCode: '&#658;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/h/',
    id: 17,
    description: 'hot, whole, ahead',
    uniCode: 'h',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/m/',
    id: 18,
    description: 'more, hammer, sum',
    uniCode: 'm',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/n/',
    id: 19,
    description: 'nice, know, funny, sun',
    uniCode: 'n',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ng/',
    id: 20,
    description: 'ring, anger, thanks, sung',
    uniCode: '&#331;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/l/',
    id: 21,
    description: 'light, valley, feel',
    uniCode: 'l',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/r/',
    id: 22,
    description: 'right, wrong, sorry, arrange',
    uniCode: 'r',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/j/',
    id: 23,
    description: 'yet, use, beauty, few',
    uniCode: 'j',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/w/',
    id: 24,
    description: 'wet, one, when, queen',
    uniCode: 'w',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/t/',
    id: 25,
    description: 'department, football',
    uniCode: '&#660;',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/i/',
    id: 26,
    description: 'kit, bid, hymn, minute',
    uniCode: '&#618;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/e/',
    id: 27,
    description: 'dress, bed, head, many',
    uniCode: 'e',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/a/',
    id: 28,
    description: 'trap, bad',
    uniCode: '&#230;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/o/',
    id: 29,
    description: 'lot, odd, wash',
    uniCode: '&#594;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/u/',
    id: 30,
    description: 'strut, mud, love, blood',
    uniCode: '&#652;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/oo/',
    id: 31,
    description: 'foot, good, put',
    uniCode: '&#650;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ee/',
    id: 32,
    description: 'fleece, sea, machine',
    uniCode: 'i &#720;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ai/',
    id: 33,
    description: 'face, day, break',
    uniCode: 'e &#618;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ie/',
    id: 34,
    description: 'price, high, try',
    uniCode: 'a &#618;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/oi/',
    id: 35,
    description: 'choice, boy',
    uniCode: '&#596; &#618;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/oo/',
    id: 36,
    description: 'goose, two, blue, group',
    uniCode: 'u &#720;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/oa/',
    id: 37,
    description: 'goat, show, no',
    uniCode: '&#601; &#650;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ou/',
    id: 38,
    description: 'mouth, now',
    uniCode: 'a &#650;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ea/',
    id: 39,
    description: 'near, here, weary',
    uniCode: '&618; &#601;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ai/',
    id: 40,
    description: 'square, fair, various',
    uniCode: 'e &#601;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ar/',
    id: 41,
    description: 'start, father',
    uniCode: '&#593; &#720;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/or/',
    id: 42,
    description: 'thought, law, north, war',
    uniCode: '&#596; &#720;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ur/',
    id: 43,
    description: 'pure, jury, cure',
    uniCode: '&#650; &#601;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/er/',
    id: 44,
    description: 'nurse, stir, learn, refer',
    uniCode: '&#604; &#720;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/a/',
    id: 45,
    description: 'about, common, standard',
    uniCode: '&#601;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/i/',
    id: 46,
    description: 'happy, radiate. glorious',
    uniCode: 'i',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ou/',
    id: 47,
    description: 'you, influence, situation',
    uniCode: 'u',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/en/',
    id: 48,
    description: 'suddenly, cotton',
    uniCode: 'n &#809;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/le/',
    id: 49,
    description: 'middle, metal',
    uniCode: 'l &#809;',
    vowel: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/ks/',
    id: 50,
    description:
      'box, fox. This phoneme is actually two phonemes, the k and s sounds.',
    uniCode: 'ks',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    phoneme: '/kw/',
    id: 51,
    description: 'queen, quick. 2 phonemes together',
    uniCode: 'kw',
    vowel: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
